"""Project files: pyproject, database setup, config, main.py, smoke test, stub modules."""

import tomllib
from importlib import resources

from migrator.concepts.models import ConceptKind, ConceptModel
from migrator.core.models import Manifest
from migrator.planning.models import FileRole, MigrationPlan
from migrator.skeleton.files import FileBuilder

BASE_DEPENDENCIES = ["fastapi>=0.111", "uvicorn[standard]>=0.30"]
BASE_DEV_DEPENDENCIES = ["pytest>=8.2", "httpx>=0.27"]

DATABASE = """
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./app.db")
engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(bind=engine, expire_on_commit=False)


class Base(DeclarativeBase):
    pass


def get_db() -> Iterator[Session]:
    with SessionLocal() as session:
        yield session
"""


README = """# {name} (Python skeleton)

Generated by code-migrator from `{source}` ({language}).
Routes, tables, request models and config are in place.
Handlers answer 501 until the logic is migrated (M6).
See `.migrator/plan.json` for where every source file goes.
"""

LIFESPAN = """
@asynccontextmanager
async def lifespan(app: FastAPI):
    Base.metadata.create_all(engine)  # tables are created on startup, like the source ORM did
    yield
"""

RUN = """
if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=int(os.getenv("PORT", "8000")))
"""

SMOKE_TEST = """
EXPECTED_ROUTES = {{
{expected}}}


def test_every_source_route_exists():
    paths = app.openapi()["paths"]
    found = {{(method.upper(), path) for path, methods in paths.items() for method in methods}}
    assert EXPECTED_ROUTES <= found, EXPECTED_ROUTES - found
"""


def render_dependencies(
    manifests: list[Manifest], source_language: str, notes: list[str]
) -> tuple[list[str], list[str]]:
    mapping = tomllib.loads(
        (resources.files("migrator.mappings") / f"{source_language}-to-python.toml").read_text()
    )
    runtime, dev = set(BASE_DEPENDENCIES), set(BASE_DEV_DEPENDENCIES)
    for manifest in manifests:
        for group, found, target in (
            ("dependencies", manifest.dependencies, runtime),
            ("dev_dependencies", manifest.dev_dependencies, dev),
        ):
            for package in found:
                if package.startswith("@types/"):
                    continue  # TypeScript type packages are not needed in Python
                mapped = mapping.get(group, {}).get(package)
                if mapped is None:
                    kind = "dev package" if group == "dev_dependencies" else "package"
                    notes.append(f"skeleton: no Python mapping for {kind} '{package}'")
                elif mapped:
                    target.add(mapped)
    return sorted(runtime), sorted(dev)


def render_project(
    plan: MigrationPlan, runtime: list[str], dev: list[str], files: FileBuilder, repo_name: str
) -> None:
    deps = "".join(f'    "{d}",\n' for d in runtime)
    dev_deps = ", ".join(f'"{d}"' for d in dev)
    files.add(
        "pyproject.toml",
        (
            f'[project]\nname = "{repo_name}-python"\nversion = "0.1.0"\n'
            f'requires-python = ">=3.12"\ndependencies = [\n{deps}]\n\n'
            f"[dependency-groups]\ndev = [{dev_deps}]\n\n"
            '[tool.pytest.ini_options]\ntestpaths = ["tests"]\npythonpath = ["."]'
        ),
    )
    readme = README.format(name=repo_name, source=plan.source_repo, language=plan.source_language)
    files.add("README.md", readme)


def render_database(files: FileBuilder) -> None:
    files.add(
        "app/database.py",
        DATABASE,
        [
            "import os",
            "from collections.abc import Iterator",
            "from sqlalchemy import create_engine",
            "from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker",
        ],
    )


def render_config(model: ConceptModel, plan: MigrationPlan, files: FileBuilder) -> None:
    path = next(
        (f.target for f in plan.files() if f.role == FileRole.CONFIG and f.target), "app/config.py"
    )
    names = [
        n.key for n in model.of_kind(ConceptKind.ENV_VAR) if n.key not in ("DATABASE_URL", "PORT")
    ]
    lines = [f'{name} = os.getenv("{name}")' for name in names]
    files.add(path, "\n".join(lines) or "# no settings found", ["import os"])
    files.note(
        path, "Settings from env vars. MIGRATOR-STUB: defaults and types are migrated in M6."
    )
    files.add(".env.example", "\n".join(f"{n.key}=" for n in model.of_kind(ConceptKind.ENV_VAR)))


def render_main(
    router_modules: list[str], model_modules: list[str], has_tables: bool, files: FileBuilder
) -> None:
    imports = ["import os", "import uvicorn", "from fastapi import FastAPI"]
    lines = []
    if has_tables:
        imports += [
            "from contextlib import asynccontextmanager",
            "from app.database import Base, engine",
        ]
        imports += [
            f"import {m.removesuffix('.py').replace('/', '.')}  # noqa: F401" for m in model_modules
        ]
        lines += [LIFESPAN, "", 'app = FastAPI(title="Migrated app", lifespan=lifespan)']
    else:
        lines.append('app = FastAPI(title="Migrated app")')
    for module in router_modules:
        alias = module.replace(".", "_")
        imports.append(f"from {module} import router as {alias}")
        lines.append(f"app.include_router({alias})")
    lines += ["", RUN]
    files.add("app/main.py", "\n".join(lines), imports)


def render_smoke_test(model: ConceptModel, files: FileBuilder) -> None:
    routes = sorted(
        (n.attributes["method"], n.attributes["path"]) for n in model.of_kind(ConceptKind.ROUTE)
    )
    expected = "".join(f"    {r!r},\n" for r in routes)
    test_code = SMOKE_TEST.format(expected=expected)
    files.add("tests/test_skeleton.py", test_code, ["from app.main import app"])


def render_stubs(plan: MigrationPlan, files: FileBuilder) -> None:
    """Every mapped source file gets a note in its target, so nothing is forgotten."""
    for file in plan.files():
        if file.target is None:
            continue
        if file.role in (FileRole.SERVICE, FileRole.UTILITY, FileRole.TEST, FileRole.GUARD):
            files.note(
                file.target,
                f"Migrated from {file.source}. MIGRATOR-STUB: logic not migrated yet (M6).",
            )
        else:
            files.add(file.target)  # make sure the file exists
