"""Git in the generated target repo: one commit per green unit, easy rollback.

This only touches the target repo that code-migrator created, never the source repo.
"""

import logging
import subprocess
from pathlib import Path

log = logging.getLogger(__name__)

AUTHOR = ["-c", "user.name=code-migrator", "-c", "user.email=code-migrator@localhost"]
GITIGNORE = ".venv/\n__pycache__/\n.pytest_cache/\n*.db\n"


class GitRepo:
    def __init__(self, path: Path) -> None:
        self.path = path

    def ensure(self) -> None:
        if (self.path / ".git").exists():
            return
        if not (self.path / ".gitignore").exists():
            (self.path / ".gitignore").write_text(GITIGNORE)
        self._git("init", "-q", "-b", "migration")
        self.commit("Skeleton generated by code-migrator")
        log.info("Started git history in %s (branch 'migration')", self.path)

    def commit(self, message: str) -> str:
        self._git("add", "-A")
        if self._git("status", "--porcelain"):
            self._git(*AUTHOR, "commit", "-q", "-m", message)
        return self.head()

    def head(self) -> str:
        return self._git("rev-parse", "--short", "HEAD")

    def restore(self, paths: list[str]) -> None:
        """Put files back as they were in the last commit; delete files that were new."""
        for path in paths:
            tracked = (
                subprocess.run(
                    ["git", "-C", str(self.path), "ls-files", "--error-unmatch", path],
                    capture_output=True,
                ).returncode
                == 0
            )
            if tracked:
                self._git("checkout", "HEAD", "--", path)
            else:
                (self.path / path).unlink(missing_ok=True)
        log.info("Restored %d file(s) to the last commit", len(paths))

    def _git(self, *args: str) -> str:
        try:
            result = subprocess.run(
                ["git", "-C", str(self.path), *args], capture_output=True, text=True
            )
        except FileNotFoundError as error:
            raise RuntimeError("git is not installed, it is needed for `migrate`") from error
        if result.returncode != 0:
            raise RuntimeError(f"git {args[0]} failed: {result.stderr.strip()}")
        return result.stdout.strip()
