import subprocess

from migrator.baseline.models import Observation, ScenarioStep, StepTrace, Trace
from migrator.migration.context import load_visible_traces, unit_context
from migrator.migration.gitrepo import GitRepo
from migrator.migration.policy import allowed_paths, check_change, check_done
from migrator.repository import LocalRepository
from tests.unit.migration.helpers import GOOD_CODE, GOOD_TEST, STUB, make_repos, plan

UNIT = plan().units[0]
SKIPPED_TEST = "import pytest\n\n@pytest.mark.skip\ndef test_x():\n    assert 1\n"


def test_allowed_paths_are_own_target_and_own_test():
    assert allowed_paths(UNIT) == ["app/calc.py", "tests/generated/test_u01.py"]


def test_check_change_blocks_protected_and_foreign_paths():
    problems = check_change(
        UNIT,
        {
            "tests/test_skeleton.py": "x = 1",
            "app/other.py": "x = 1",
            "../../etc/passwd": "x",
            ".migrator/state.json": "{}",
        },
    )
    text = "\n".join(problems)
    assert "tests/test_skeleton.py is protected" in text
    assert "app/other.py is not allowed" in text
    assert "../../etc/passwd is not allowed" in text
    assert ".migrator/state.json is protected" in text


def test_check_change_finds_syntax_errors_and_skipped_tests():
    problems = check_change(
        UNIT,
        {
            "app/calc.py": "def add(:\n",
            "tests/generated/test_u01.py": SKIPPED_TEST,
        },
    )
    assert any("syntax error on line 1" in p for p in problems)
    assert any("skipped or xfail" in p for p in problems)


def test_check_done_needs_no_stubs_and_real_tests():
    assert (
        check_done(UNIT, {"app/calc.py": GOOD_CODE, "tests/generated/test_u01.py": GOOD_TEST}) == []
    )
    problems = check_done(
        UNIT, {"app/calc.py": STUB, "tests/generated/test_u01.py": "def helper(): pass"}
    )
    assert any("still has a stub" in p for p in problems)
    assert any("must contain real tests" in p for p in problems)


def trace(name: str, path: str, holdout: bool = False) -> Trace:
    step = StepTrace(
        request=ScenarioStep(
            method="GET",
            path=path,
            headers={"Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3In0.sig"},
        ),
        observed=Observation(status=200, body={"sum": 5}),
    )
    return Trace(scenario=name, holdout=holdout, steps=[step])


def test_context_has_source_target_traces_and_only_claims(make_repo):
    source, target = make_repos(make_repo)
    traces = [trace("sum works", "/sum"), trace("other route", "/health")]
    values = unit_context(UNIT, plan(), LocalRepository(source), target, traces)
    assert "export function add" in values["source_files"]
    assert "MIGRATOR-STUB" in values["target_files"]
    assert "sum works" in values["traces"] and "other route" not in values["traces"]
    assert '"sub": "7"' in values["traces"] and "eyJ" not in values["traces"]
    assert values["risks"] == "- integer overflow"


def test_hold_out_traces_are_never_loaded(tmp_path):
    visible = trace("visible", "/sum").model_dump()
    sneaky = trace("held out", "/sum", holdout=True).model_dump()
    (tmp_path / "traces.json").write_text(__import__("json").dumps([visible, sneaky]))
    (tmp_path / "holdout.json").write_text(__import__("json").dumps([sneaky]))
    assert [t.scenario for t in load_visible_traces(tmp_path)] == ["visible"]


def test_git_restore_puts_back_tracked_files_and_deletes_new_ones(make_repo):
    _, target = make_repos(make_repo)
    git = GitRepo(target)
    git.ensure()
    (target / "app/calc.py").write_text("changed")
    (target / "tests/generated").mkdir(parents=True)
    (target / "tests/generated/test_u01.py").write_text("new")
    git.restore(["app/calc.py", "tests/generated/test_u01.py"])
    assert (target / "app/calc.py").read_text() == STUB
    assert not (target / "tests/generated/test_u01.py").exists()
    log = subprocess.run(
        ["git", "-C", str(target), "log", "--format=%an %s"], capture_output=True, text=True
    )
    assert log.stdout.strip() == "code-migrator Skeleton generated by code-migrator"
